# name: pkg-test1

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# permissions:
#   contents: read

# jobs:
#   pkg-test:
#     runs-on: ubuntu-latest
#     # env:
#     #   GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

#     steps:
#       - uses: actions/checkout@v4

#       - uses: r-lib/actions/setup-r@v2
#         with:
#           r-version: '4.2.1'
#           use-public-rspm: true

#       - uses: r-lib/actions/setup-r-dependencies@v2
#         with:
#           extra-packages: devtools

#       - name: install-opusreader
#         run: devtools::install_github("pierreroudier/opusreader")
#         shell: Rscript {0}

#       - name: install-opusreader2
#         run: devtools::install_github("spectral-cockpit/opusreader2@opusreader2_v0.5.0.9000")
#         shell: Rscript {0}

#       - name: pkg-test
#         run: devtools::test(stop_on_failure = T)
#         shell: Rscript {0}

name: pkg-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.2.1']
        #r-version: ['3.6.3', '4.2.1']

    steps:
      - uses: actions/checkout@v4
      
      - name: set-up-R-${{ matrix.r-version }}
        uses: r-lib/actions/setup-r2@v2
        with:
          r-version: ${{ matrix.r-version }}
          
      - name: install-dependencies
        run: |
          install.packages(c("devtools", "Rcpp"))
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: install-opusreader
        run: devtools::install_github("pierreroudier/opusreader")
        shell: Rscript {0}

      - name: install-opusreader2
        run: devtools::install_github("spectral-cockpit/opusreader2@opusreader2_v0.5.0.9000")
        shell: Rscript {0}

      - name: pkg-test
        run: devtools::test(stop_on_failure = T)
        shell: Rscript {0}
        
      # - name: Check
      #   run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
      #   shell: Rscript {0}

